[MEMORY]
ZEROPAGE = { start = "$000000", size = "$100", type = "rw" }
STACK = { start = "$000100", size = "$100", type = "rw" }
LORAM = { start = "$000200", size = "$1800", type = "rw" }

FASTROM = { start = "$C00000", size = "$400000", type = "ro", fill = "$00" }
SLOWROM0 = { start = "$400000", size = "$8000", type = "ro", fill = "$00" }
SLOWROM1 = { start = "$408000", size = "$7FB0", type = "ro", fill = "$00" }
HEADER = { start = "$40FFB0", size = "$30", type = "ro" }
VECTORS = { start = "$40FFE0", size = "$20", type = "ro" }
SLOWROM2 = { start = "$410000", size = "$3E0000", type = "ro", fill = "$00" }
SLOWROM3 = { start = "$3E8000", size = "$8000", type = "ro", fill = "$00" }
SLOWROM4 = { start = "$3F8000", size = "$8000", type = "ro", fill = "$00" }

[SECTIONS]
ZEROPAGE = { load = "ZEROPAGE", type = "bss" }
LORAM = { load = "LORAM", type = "bss" }

HOME = { load = "FASTROM", type = "ro" }

# Mesen-S is dumb and checks for vectors to jump to > $408000 in ExHiROM
VECTORJUMP = { load = "SLOWROM1", type = "ro" }
HEADER = { load = "HEADER", type = "ro" }
VECTORS = { load = "VECTORS", type = "ro" }
