[MEMORY]
INES_HEADER = { start = "0", size = "16", type = "ro" }
PRG0 = { start = "$8000", size = "$4000", type = "ro", fill = "0" }
PRG1 = { start = "$8000", size = "$4000", type = "ro", fill = "0" }
KERNEL = { start = "$C000", size = "$3FFA", type = "ro", fill = "0" }
VECTORS = { start = "$FFFA", size = "6", type = "ro", fill = "0" }

[SECTIONS]
INES_HEADER = { load = "INES_HEADER", type = "ro" }
PRG0 = { load = "PRG0", type = "ro" }
PRG1 = { load = "PRG1", type = "ro" }
KERNEL = { load = "KERNEL", type = "ro" }
VECTORS = { load = "VECTORS", type = "ro" }
