[MEMORY]
ZEROPAGE = { start = "$800000", size = "$100",   type = "rw" }
STACK    = { start = "$800100", size = "$100",   type = "rw" }
LORAM    = { start = "$800200", size = "$1800",  type = "rw" }
WRAM0    = { start = "$7E2000", size = "$E000",  type = "rw" }
WRAM1    = { start = "$7F0000", size = "$10000", type = "rw" }

FASTROM  = { start = "$C00000", size = "$400000", type = "ro", fill = "$00" }
SLOWROM0 = { start = "$400000", size = "$8000",   type = "ro", fill = "$00" }
SLOWROM1 = { start = "$408000", size = "$7FB0",   type = "ro", fill = "$00" }
HEADER   = { start = "$40FFB0", size = "$30",     type = "ro" }
VECTORS  = { start = "$40FFE0", size = "$20",     type = "ro" }
SLOWROM2 = { start = "$410000", size = "$3E0000", type = "ro", fill = "$00" }
SLOWROM3 = { start = "$3E8000", size = "$8000",   type = "ro", fill = "$00" }
SLOWROM4 = { start = "$3F8000", size = "$8000",   type = "ro", fill = "$00" }

[SECTIONS]
ZEROPAGE   = { load = "ZEROPAGE", type = "dp" }
LORAM      = { load = "LORAM",    type = "bss", define = true }
WRAM0      = { load = "WRAM0",    type = "bss", define = true }
WRAM1      = { load = "WRAM1",    type = "bss", define = true }

CORE       = { load = "FASTROM",  type = "ro" }

# Mesen-S is dumb and checks for vectors to jump to > $408000 in ExHiROM
VECTORJUMP = { load = "SLOWROM1", type = "ro" }
HEADER     = { load = "HEADER",   type = "ro" }
VECTORS    = { load = "VECTORS",  type = "ro" }
