[package]
name = "nyasm"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
toml = "0.8"
serde = "1"
serde_derive = "1"
tracing = "0.1"
tracing-subscriber = "0.3"

indexmap = { version = "2", features = ["serde"] }

