; vim: ft=pasm

SECTION "INES_HEADER"

HDR_PRG_ROM_BANKS EQU 2     ; 2 - 16k banks
HDR_CHR_ROM_BANKS EQU 0     ; 0 - 8k banks
HDR_MAPPER_ID EQU 30        ; unrom 512
HDR_SUBMAPPER_ID EQU 0
HDR_FOUR_SCREEN EQU 1
HDR_MIRRORING EQU 0
HDR_BATTERY EQU 0
HDR_PRG_NVRAM_SIZE EQU 0
HDR_PRG_RAM_SIZE EQU 0
HDR_CHR_NVRAM_SIZE EQU 0
HDR_CHR_RAM_SIZE EQU 9      ; 32k - 64 * 2^n bytes
HDR_REGION EQU 0            ; ntsc

BYTE "NES", $1A
BYTE HDR_PRG_ROM_BANKS
BYTE HDR_CHR_ROM_BANKS
BYTE ((HDR_MAPPER_ID & $0F) << 4) | (HDR_FOUR_SCREEN << 3) | (HDR_BATTERY << 1) | HDR_MIRRORING
BYTE (HDR_MAPPER_ID & $F0) | %1000
BYTE (HDR_SUBMAPPER_ID << 4) | ((HDR_MAPPER_ID & $F00) >> 8)
BYTE ((HDR_PRG_ROM_BANKS & $F00) >> 4) | ((HDR_CHR_ROM_BANKS & $F00) >> 8)
BYTE (HDR_PRG_NVRAM_SIZE << 4) | HDR_PRG_RAM_SIZE
BYTE (HDR_CHR_NVRAM_SIZE << 4) | HDR_CHR_RAM_SIZE
BYTE HDR_REGION
BYTE 0, 0, 0
